# Generated by Django 3.2 on 2021-05-17 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import insects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('eName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('thumb', models.ImageField(default=None, upload_to=insects.models.save_to_slug)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('eName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('thumb', models.ImageField(upload_to=insects.models.save_to_slug)),
            ],
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('eName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('thumb', models.ImageField(upload_to=insects.models.save_to_slug)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insects.family')),
            ],
        ),
        migrations.CreateModel(
            name='Insect',
            fields=[
                ('eName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('characteristic', models.TextField(default='null')),
                ('value', models.TextField(default='null')),
                ('reality', models.TextField(default='null')),
                ('protective', models.TextField(default='null')),
                ('distribution', models.TextField(default='null')),
                ('detail', models.TextField(default='null')),
                ('thumb', models.ImageField(blank=True, upload_to=insects.models.save_to_slug)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insects.genus')),
            ],
        ),
        migrations.CreateModel(
            name='Insect_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to=insects.models.save_to)),
                ('placeholder', models.CharField(default=None, max_length=100)),
                ('subset', models.CharField(default=None, max_length=20)),
                ('insect', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='insects.insect')),
            ],
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('eName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('thumb', models.ImageField(blank=True, upload_to=insects.models.save_to_slug)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('name', models.CharField(default=None, max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='insects.insect_image')),
            ],
        ),
        migrations.CreateModel(
            name='Phylum',
            fields=[
                ('eName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('thumb', models.ImageField(default=None, upload_to=insects.models.save_to_slug)),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insects.kingdom')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('eName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('thumb', models.ImageField(upload_to=insects.models.save_to_slug)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insects.classes')),
            ],
        ),
        migrations.CreateModel(
            name='InsectTest',
            fields=[
                ('eName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('characteristic', models.TextField(default='null')),
                ('value', models.TextField(default='null')),
                ('reality', models.TextField(default='null')),
                ('protective', models.TextField(default='null')),
                ('distribution', models.TextField(default='null')),
                ('detail', models.TextField(default='null')),
                ('thumb', models.ImageField(blank=True, default=None, upload_to=insects.models.save_to_slug)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insects.genus')),
            ],
        ),
        migrations.CreateModel(
            name='Insect_downloadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=insects.models.save_zip_to_slug)),
                ('insect', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='insects.insect')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insects.order'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='phylum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insects.phylum'),
        ),
    ]
