# Generated by Django 3.2 on 2021-05-23 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0002_new_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rect_New_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='insects.new_image')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
