# Generated by Django 3.2 on 2021-05-25 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0003_auto_20210523_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_image',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='insect_image',
            name='insect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insects.insect'),
        ),
    ]
