# Generated by Django 3.2 on 2021-05-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0004_auto_20210525_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_image',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
