# Generated by Django 3.2.3 on 2022-02-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0006_remove_insect_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminupload', models.FileField(upload_to='media')),
                ('title', models.CharField(max_length=50)),
                ('thumb', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
